Repository LT-Students/DigitalOffice-MessageService, pull requests merged in 2021-07, with the labels that each got.

#30 add logic of creating default workspace for new project
  src/MessageService.Broker/Consumers/CreateWorkspaceConsumer.cs
  src/MessageService.Business/Commands/Workspace/CreateWorkspaceCommand.cs
  src/MessageService.Business/Commands/Workspace/RemoveWorkspaceCommand.cs
  src/MessageService.Data.Provider.MsSql.Ef/MessageServiceDbContext.cs
  src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210104201900_ChangeWorkspace.cs
  src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210621144000_UpdateWorkspace.cs
  src/MessageService.Data.Provider/IDataProvider.cs
  src/MessageService.Data/ChannelRepository.cs
  src/MessageService.Data/ChannelUserRepository.cs
  src/MessageService.Data/Interfaces/IChannelRepository.cs
  src/MessageService.Data/Interfaces/IChannelUserRepository.cs
  src/MessageService.Data/Interfaces/IWorkspaceRepository.cs
  src/MessageService.Data/Interfaces/IWorkspaceUserRepository.cs
  src/MessageService.Data/WorkspaceRepository.cs
  src/MessageService.Data/WorkspaceUserRepository.cs
  src/MessageService.Mappers/Db/DbChannelMapper.cs
  src/MessageService.Mappers/Db/DbChannelUserMapper.cs
  src/MessageService.Mappers/Db/DbWorkspaceMapper.cs
  src/MessageService.Mappers/Db/DbWorkspaceUserMapper.cs
  src/MessageService.Mappers/Db/Interfaces/IDbChannelMapper.cs
  src/MessageService.Mappers/Db/Interfaces/IDbChannelUserMapper.cs
  src/MessageService.Mappers/Db/Interfaces/IDbWorkspaceMapper.cs
  src/MessageService.Mappers/Db/Interfaces/IDbWorkspaceUserMapper.cs
  src/MessageService.Models.Db/DbChannel.cs
  src/MessageService.Models.Db/DbChannelUser.cs
  src/MessageService.Models.Db/DbWorkspace.cs
  src/MessageService.Models.Db/DbWorkspaceAdmin.cs
  src/MessageService.Models.Db/DbWorkspaceUsers.cs
  src/MessageService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/MessageService/Startup.cs
  src/MessageService/appsettings.json
  test/MessageService.Broker.UnitTests/CreateWorkspaceConsumerTests.cs
  test/MessageService.Business.UnitTests/Workspace/CreateWorkspaceCommandTests.cs
  test/MessageService.Business.UnitTests/Workspace/RemoveWorkspaceCommandTests.cs
  test/MessageService.Data.UnitTests/ChannelRepositoryTests.cs
  test/MessageService.Data.UnitTests/ChannelUserRepositoryTests.cs
  test/MessageService.Data.UnitTests/WorkspaceRepositoryTests.cs
  test/MessageService.Data.UnitTests/WorkspaceUserRepositoryTests.cs
  test/MessageService.Mappers.UnitTests/Workspace/DbChannelMapperTests.cs
  test/MessageService.Mappers.UnitTests/Workspace/DbChannelUserMapperTests.cs
  test/MessageService.Mappers.UnitTests/Workspace/DbWorkspaceMapperTests.cs
  test/MessageService.Mappers.UnitTests/Workspace/DbWorkspaceUserMapperTests.cs
Labels: enhancement

#31 add create smtp consumer
  Common.Configurations.targets
  src/MessageService.Broker/Consumers/CreateSMTPCredentialsConsumer.cs
  src/MessageService.Broker/Helpers/BaseEmailSender.cs
  src/MessageService.Broker/Helpers/EmailResender.cs
  src/MessageService.Broker/Helpers/EmailSender.cs
  src/MessageService.Data.Provider.MsSql.Ef/MessageServiceDbContext.cs
  src/MessageService.Data.Provider.MsSql.Ef/Migrations/20210701095500_AddSMTP.cs
  src/MessageService.Data.Provider/IDataProvider.cs
  src/MessageService.Data/Interfaces/ISMTPCredentialsRepository.cs
  src/MessageService.Data/SMTPCredentialsRepository.cs
  src/MessageService.Mappers/Db/DbSMTPCredentialsMapper.cs
  src/MessageService.Mappers/Db/Interfaces/IDbSMTPCredentialsMapper.cs
  src/MessageService.Models.Db/DbSMTPCredentials.cs
  src/MessageService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/MessageService/Startup.cs
  src/MessageService/appsettings.json
  test/MessageService.Broker.UnitTests/CreateSMTPConsumerTests.cs
  test/MessageService.Data.UnitTests/SMTPCredentialRepositoryTests.cs
  test/MessageService.Mappers.UnitTests/DbSMTPCredentialMapperTests.cs
Labels: enhancement

#32 change class to record
  src/MessageService.Models.Dto/Models/Emails/EmailInfo.cs
  src/MessageService.Models.Dto/Models/Emails/EmailTemplateTextInfo.cs
  src/MessageService.Models.Dto/Models/Emails/UnsentEmailInfo.cs
  src/MessageService.Models.Dto/Models/ImageInfo.cs
  src/MessageService.Models.Dto/Requests/EmailTemplate/EditEmailTemplateRequest.cs
  src/MessageService.Models.Dto/Requests/EmailTemplate/EmailTemplateRequest.cs
  src/MessageService.Models.Dto/Requests/Workspace/WorkspaceRequest.cs
  src/MessageService.Models.Dto/Responses/UnsentEmailsResponse.cs
Labels: enhancement

#34 fix github actions
  .github/workflows/main.yml
Labels: documentation

#36 fixed pagination
  src/MessageService.Data/UnsentEmailRepository.cs
  src/MessageService.Data/WorkspaceUserRepository.cs
  test/MessageService.Data.UnitTests/UnsentEmailRepositoryTests.cs
Labels: bug

#37 docs/change_actions
  .github/workflows/main.yml
Labels: documentation

#38 add find sample letters
  src/MessageService.Broker/Consumers/SendEmailConsumer.cs
  src/MessageService.Business/Commands/EmailTemplate/CreateEmailTemplateCommand.cs
  src/MessageService.Business/Commands/EmailTemplate/DisableEmailTemplateCommand.cs
  src/MessageService.Business/Commands/EmailTemplate/EditEmailTemplateCommand.cs
  src/MessageService.Business/Commands/EmailTemplate/FindEmailTemplateCommand.cs
  src/MessageService.Business/Commands/EmailTemplate/Interfaces/IFindEmailTemplateCommand.cs
  src/MessageService.Data/EmailTemplateRepository.cs
  src/MessageService.Data/Interfaces/IEmailTemplateRepository.cs
  src/MessageService.Mappers/Db/DbEmailTemplateTextMapper.cs
  src/MessageService.Mappers/Db/Interfaces/IDbEmailTemplateTextMapper.cs
  src/MessageService.Mappers/Models/EmailTemplateInfoMapper.cs
  src/MessageService.Mappers/Models/EmailTemplateTextInfoMapper.cs
  src/MessageService.Mappers/Models/Interfaces/IEmailTemplateInfoMapper.cs
  src/MessageService.Mappers/Models/Interfaces/IEmailTemplateTextInfoMapper.cs
  src/MessageService.Models.Dto/Models/Emails/EmailTemplateInfo.cs
  src/MessageService.Models.Dto/Models/Emails/EmailTemplateTextInfo.cs
  src/MessageService.Models.Dto/Requests/EmailTemplate/EditEmailTemplateRequest.cs
  src/MessageService.Models.Dto/Requests/EmailTemplate/EmailTemplateRequest.cs
  src/MessageService.Models.Dto/Requests/EmailTemplate/EmailTemplateTextRequest.cs
  src/MessageService.Models.Dto/Responses/EmailTemplatesResponse.cs
  src/MessageService/Controllers/EmailTemplateController.cs
  test/MessageService.Broker.UnitTests/SendEmailConsumerTests.cs
  test/MessageService.Business.UnitTests/EmailTemplate/CreateEmailTemplateCommandTests.cs
  test/MessageService.Business.UnitTests/EmailTemplate/DisableEmailTemplateCommandTests.cs
  test/MessageService.Business.UnitTests/EmailTemplate/EditEmailTemplateCommandTests.cs
  test/MessageService.Business.UnitTests/EmailTemplate/FindEmailTemplatesCommandTests.cs
  test/MessageService.Data.UnitTests/EmailTemplateRepositoryTests.cs
  test/MessageService.Mappers.UnitTests/EmailTemplate/DbEmailTemplateMapperTests.cs
  test/MessageService.Mappers.UnitTests/EmailTemplate/EditDbEmailTemplateMapperTests.cs
  test/MessageService.Mappers.UnitTests/EmailTemplate/EmailTemplateInfoMapperTests.cs
  test/MessageService.Mappers.UnitTests/EmailTemplate/EmailTemplateTextInfoMapperTests.cs
  test/MessageService.Validation.UnitTests/CreateEmailTemplateValidatorTests.cs
  test/MessageService.Validation.UnitTests/EditEmailTemplateValidatorTests.cs
Labels: enhancement
